--멤버테이블
CREATE TABLE MEMBER(
MID NVARCHAR2(20) CONSTRAINT PK_MEMBER PRIMARY KEY,
KAKAOID NVARCHAR2(20) UNIQUE,
NAVERID NVARCHAR2(20) UNIQUE,
MPASSWORD NVARCHAR2(20),
MNAME NVARCHAR2(10),
MPOSTNUM NVARCHAR2(20),
MADDRESS1 NVARCHAR2(50),
MADDRESS2 NVARCHAR2(20),
MADDRESS3 NVARCHAR2(20),
MPHONE NVARCHAR2(20),
MEMAIL NVARCHAR2(30),
MEMAILID NVARCHAR2(20),
MEDOMAIN NVARCHAR2(20),
MBIRTH NVARCHAR2(20),
MCLASS NVARCHAR2(10),
MVERIFY varchar2(1) default 'n' not null,
MBLACK NUMBER(1) default '0' not null,
MFILENAME NVARCHAR2(50),
MFAVORITE NVARCHAR2(10),
MCONTENTS NVARCHAR2(20)
);
SELECT * FROM MEMBER;
DELETE FROM MEMBER WHERE MID='admin';
COMMIT;



DROP TABLE PRODUCT;
--상품테이블
CREATE TABLE PRODUCT(
PPRODUCT NVARCHAR2(20),
PPRODUCT2 NVARCHAR2(20),
PMID NVARCHAR2(20) CONSTRAINT FK_PMID REFERENCES MEMBER(MID) ON DELETE CASCADE,
PID NVARCHAR2 (20) CONSTRAINT PK_PRODUCT PRIMARY KEY,
PNAME NVARCHAR2 (30),
PPRICE NUMBER(5),
PSTOCK NUMBER(5),
PDESC NVARCHAR2 (50),
PRATE NUMBER(5),
PFILENAME NVARCHAR2 (50),
PDATE DATE);

DELETE FROM PRODUCT WHERE PID='12312';
COMMIT;
SELECT * FROM PRODUCT;
UPDATE PRODUCT SET PRATE= + 3 WHERE PID='A-10';
DROP TABLE PRODUCT;
--상품리뷰 테이블
 CREATE TABLE PRODUCTREVIEW(
PRNUMBER NUMBER CONSTRAINT PK_PRODUCTREVIEW PRIMARY KEY,
PRPMID NVARCHAR2(20) CONSTRAINT FK_PRPMID REFERENCES MEMBER(MID) ON DELETE CASCADE,
PRID NVARCHAR2(20) CONSTRAINT FK_PRID REFERENCES PRODUCT(PID) ON DELETE CASCADE,
PRMID NVARCHAR2(20) CONSTRAINT FK_PRMID REFERENCES MEMBER(MID) ON DELETE CASCADE,
PRCONTENTS NVARCHAR2(100),
STAR NUMBER(5),
PRDATE DATE);
DROP TABLE PRODUCTREVIEW;

--장바구니 테이블
CREATE TABLE CART(
    CART_ID NUMBER CONSTRAINT PK_CART PRIMARY KEY,
    USER_ID NVARCHAR2(50)CONSTRAINT FK_USER REFERENCES MEMBER(MID), 
    PRODUCT_ID NVARCHAR2(50)CONSTRAINT FK_PRODUCT REFERENCES PRODUCT(PID),
    AMOUNT NUMBER DEFAULT 0);
SELECT * FROM CART;
DROP TABLE CART;
--장바구니 시퀀스
CREATE SEQUENCE CART_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
COMMIT;
DROP SEQUENCE CART_SEQ;
SELECT * FROM PRODUCTREVIEW;
--상품리뷰 시퀀스
CREATE SEQUENCE PREVIEW_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  COMMIT;

DROP SEQUENCE PREVIEW_SEQ;
--상품문의테이블 
CREATE TABLE PCOMMENT(
PCNUMBER NUMBER CONSTRAINT PK_PCNUMBER PRIMARY KEY,
PCPMID NVARCHAR2(20) CONSTRAINT FK_PCPMID REFERENCES MEMBER(MID) ON DELETE CASCADE,
PCPID NVARCHAR2(20) CONSTRAINT FK_PCPID REFERENCES PRODUCT(PID) ON DELETE CASCADE,
PCMID NVARCHAR2(20)CONSTRAINT FK_PCMID REFERENCES MEMBER(MID) ON DELETE CASCADE,
PCONTENTS NVARCHAR2(100),
PCRESULT NVARCHAR2(30),
SECRET NUMBER(1) default '0' not null,
RESULT NVARCHAR2(20),
PCDATE DATE,
PCREDATE DATE);
DROP TABLE PCOMMENT;
SELECT * FROM PCOMMENT;

--상품문의 시퀀스
CREATE SEQUENCE PCOMMENT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
DROP TABLE PCOMMENT;
SELECT * FROM PCOMMENT;
COMMIT;
DROP SEQUENCE PCOMMENT_SEQ;

--게시판 테이블
SELECT * FROM ABOARD;
CREATE TABLE ABOARD(
AMID NVARCHAR2(20) CONSTRAINT FK_AMID REFERENCES MEMBER(MID) ON DELETE CASCADE,
ANUM NUMBER CONSTRAINT PK_BOARD PRIMARY KEY,
ADATE DATE,
ATYPE NVARCHAR2(20),
ATITLE NVARCHAR2(40),
ACONTENTS NVARCHAR2(500),
AHITS NUMBER,
AFILENAME NVARCHAR2(100)
);
DROP TABLE ABOARD;
--게시판시퀀스
CREATE SEQUENCE ABOARD_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
DROP SEQUENCE ABOARD_SEQ;
--게시판댓글 테이블
CREATE TABLE ABOARDCOMMENT(
CNUM NUMBER CONSTRAINT PK_COMMENT PRIMARY KEY,
ACNUM NUMBER CONSTRAINT FK_ACNUM REFERENCES ABOARD(ANUM) ON DELETE CASCADE,
CWRITER NVARCHAR2(20) CONSTRAINT FK_CWRITER REFERENCES MEMBER(MID) ON DELETE CASCADE,
CCONTENTS NVARCHAR2(2000)
);
DROP TABLE ABOARDCOMMENT;
--게시판댓글 시퀀스
CREATE SEQUENCE CNUM_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
DROP SEQUENCE CNUM_SEQ;

COMMIT;
SELECT
 		  C.CART_ID AS cart_id,
 		  C.USER_ID AS user_id,
 		  C.PRODUCT_ID AS product_id,
 		  P.PID AS pid,
 		  P.PFILENAME AS pfilename,
 		  M.MNAME AS mname,
 		  P.PNAME AS pname,
 		  C.AMOUNT AS amount,
 		  P.PPRICE AS pprice,
 		  (PPRICE * AMOUNT)money,
          p.PMID AS sale_id
		  FROM MEMBER M, PRODUCT P, CART C 
 		  WHERE M.MID = C.USER_ID AND P.PID = C.PRODUCT_ID AND C.USER_ID='qkrxogns1'
		  ORDER BY
		  C.CART_ID;
CREATE TABLE BUY(
PBNUM NUMBER(5),
PBNAME NVARCHAR2(30),
PBPRICE NUMBER(5),
PBPID NVARCHAR2(30),
PBMID NVARCHAR2(30),
PBPMID NVARCHAR2(30),
PBFILENAME NVARCHAR2(30),
PBAMOUT NUMBER(5));
SELECT * FROM BUY;
DROP TABLE BUY;

--구매 테이블
CREATE TABLE BUY(
PBNUM NUMBER(5) CONSTRAINT PK_BUY PRIMARY KEY,
PBNAME NVARCHAR2(30),
PBPID NVARCHAR2(30) CONSTRAINT FK_PBPID REFERENCES PRODUCT(PID) ON DELETE CASCADE,
PBMID NVARCHAR2(30) CONSTRAINT FK_PBMID REFERENCES MEMBER(MID),
PBPMID NVARCHAR2(30) CONSTRAINT FK_PBPMID REFERENCES MEMBER(MID),
PBADDRESS NVARCHAR2(100),
PBPRICE NUMBER(9),
PBAMOUT NUMBER(9),
PBFILENAME NVARCHAR2(50),
PBDATE DATE);
SELECT * FROM BUY;
COMMIT;
DROP TABLE BUY;
--구매테이블 시퀀스
CREATE SEQUENCE BUY_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
DROP SEQUENCE BUY_SEQ;
         

